version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - example-backend
      - example-frontend
    restart: unless-stopped

  example-backend:
    build:
      context: ./example-backend
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=exampledb
    depends_on:
      - db
      - redis
    restart: unless-stopped

  example-frontend:
    build:
      context: ./example-frontend
      dockerfile: Dockerfile
    depends_on:
      - example-backend
      - redis
    restart: unless-stopped

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

  db:
    image: postgres:13.2-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: exampledb
    ports:
      - "5433:5432"
    volumes:
      - ./database:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  redis-data:
