version: '3.8'

services:
  example-backend:
    build:
      context: ./example-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  example-frontend:
    build:
      context: ./example-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - example-backend
