version: '3.8'

services:
  example-backend:
    build:
      context: ./example-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis

  example-frontend:
    build:
      context: ./example-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - example-backend
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data: