version: '3.8'

services:
  simple-web-service:
    image: devopsdockeruh/simple-web-service:ubuntu
    container_name: simple-web-service
    platform: linux/amd64
    command: server
    ports:
      - "8080:8080"
    restart: always
